
export const LANGUAGES = [
    { value: 'en', label: 'English' },
    { value: 'si', label: 'Sinhala' },
    { value: 'ta', label: 'Tamil' },
    { value: 'hi', label: 'Hindi' },
    { value: 'zh', label: 'Mandarin' },
    { value: 'fr', label: 'French' },
    { value: 'de', label: 'German' },
    { value: 'ru', label: 'Russian' },
    { value: 'it', label: 'Italian' },
    { value: 'ja', label: 'Japanese' },
    { value: 'ko', label: 'Korean' },
    { value: 'es', label: 'Spanish' },
    { value: 'ar', label: 'Arabic' },
    { value: 'pt', label: 'Portuguese' },
    { value: 'nl', label: 'Dutch' },
    { value: 'sv', label: 'Swedish' },
    { value: 'tr', label: 'Turkish' },
    { value: 'pl', label: 'Polish' },
    { value: 'he', label: 'Hebrew' },
    { value: 'id', label: 'Indonesian' },
    { value: 'th', label: 'Thai' },
    { value: 'vi', label: 'Vietnamese' },
    { value: 'ms', label: 'Malay' },
    { value: 'fa', label: 'Persian' },
    { value: 'ro', label: 'Romanian' },
    { value: 'bg', label: 'Bulgarian' },
    { value: 'uk', label: 'Ukrainian' },
    { value: 'hu', label: 'Hungarian' },
    { value: 'fi', label: 'Finnish' },
    { value: 'da', label: 'Danish' },
    { value: 'cs', label: 'Czech' },
    { value: 'sk', label: 'Slovak' },
    { value: 'el', label: 'Greek' },
    { value: 'no', label: 'Norwegian' },
    { value: 'sr', label: 'Serbian' }
  ];
  
  export const COUNTRIES = [
    { value: 'AF', label: 'Afghanistan'},
    { value: 'AL', label: 'Albania'},
    { value: 'DZ', label: 'Algeria'},
    { value: 'AD', label: 'Andorra'},
    { value: 'AO', label: 'Angola'},
    { value: 'AG', label: 'Antigua and Barbuda'},
    { value: 'AR', label: 'Argentina'},
    { value: 'AM', label: 'Armenia'},
    { value: 'AU', label: 'Australia'},
    { value: 'AT', label: 'Austria'},
    { value: 'AZ', label: 'Azerbaijan'},
    { value: 'BS', label: 'Bahamas'},
    { value: 'BH', label: 'Bahrain'},
    { value: 'BD', label: 'Bangladesh'},
    { value: 'BB', label: 'Barbados'},
    { value: 'BY', label: 'Belarus'},
    { value: 'BE', label: 'Belgium'},
    { value: 'BZ', label: 'Belize'},
    { value: 'BJ', label: 'Benin'},
    { value: 'BT', label: 'Bhutan'},
    { value: 'BO', label: 'Bolivia'},
    { value: 'BA', label: 'Bosnia and Herzegovina'},
    { value: 'BW', label: 'Botswana'},
    { value: 'BR', label: 'Brazil'},
    { value: 'BN', label: 'Brunei'},
    { value: 'BG', label: 'Bulgaria'},
    { value: 'BF', label: 'Burkina Faso'},
    { value: 'BI', label: 'Burundi'},
    { value: 'KH', label: 'Cambodia'},
    { value: 'CM', label: 'Cameroon'},
    { value: 'CA', label: 'Canada'},
    { value: 'CV', label: 'Cape Verde'},
    { value: 'CF', label: 'Central African Republic'},
    { value: 'TD', label: 'Chad'},
    { value: 'CL', label: 'Chile'},
    { value: 'CN', label: 'China'},
    { value: 'CO', label: 'Colombia'},
    { value: 'KM', label: 'Comoros'},
    { value: 'CG', label: 'Congo'},
    { value: 'CD', label: 'Congo, Democratic Republic'},
    { value: 'CR', label: 'Costa Rica'},
    { value: 'CI', label: 'Côte d\'Ivoire'},
    { value: 'HR', label: 'Croatia'},
    { value: 'CU', label: 'Cuba'},
    { value: 'CY', label: 'Cyprus'},
    { value: 'CZ', label: 'Czech Republic'},
    { value: 'DK', label: 'Denmark'},
    { value: 'DJ', label: 'Djibouti'},
    { value: 'DM', label: 'Dominica'},
    { value: 'DO', label: 'Dominican Republic'},
    { value: 'EC', label: 'Ecuador'},
    { value: 'EG', label: 'Egypt'},
    { value: 'SV', label: 'El Salvador'},
    { value: 'GQ', label: 'Equatorial Guinea'},
    { value: 'ER', label: 'Eritrea'},
    { value: 'EE', label: 'Estonia'},
    { value: 'ET', label: 'Ethiopia'},
    { value: 'FJ', label: 'Fiji'},
    { value: 'FI', label: 'Finland'},
    { value: 'FR', label: 'France'},
    { value: 'GA', label: 'Gabon'},
    { value: 'GM', label: 'Gambia'},
    { value: 'GE', label: 'Georgia'},
    { value: 'DE', label: 'Germany'},
    { value: 'GH', label: 'Ghana'},
    { value: 'GR', label: 'Greece'},
    { value: 'GD', label: 'Grenada'},
    { value: 'GT', label: 'Guatemala'},
    { value: 'GN', label: 'Guinea'},
    { value: 'GW', label: 'Guinea-Bissau'},
    { value: 'GY', label: 'Guyana'},
    { value: 'HT', label: 'Haiti'},
    { value: 'HN', label: 'Honduras'},
    { value: 'HU', label: 'Hungary'},
    { value: 'IS', label: 'Iceland'},
    { value: 'IN', label: 'India'},
    { value: 'ID', label: 'Indonesia'},
    { value: 'IR', label: 'Iran'},
    { value: 'IQ', label: 'Iraq'},
    { value: 'IE', label: 'Ireland'},
    { value: 'IL', label: 'Israel'},
    { value: 'IT', label: 'Italy'},
    { value: 'JM', label: 'Jamaica'},
    { value: 'JP', label: 'Japan'},
    { value: 'JO', label: 'Jordan'},
    { value: 'KZ', label: 'Kazakhstan'},
    { value: 'KE', label: 'Kenya'},
    { value: 'KI', label: 'Kiribati'},
    { value: 'KP', label: 'North Korea'},
    { value: 'KR', label: 'South Korea'},
    { value: 'KW', label: 'Kuwait'},
    { value: 'KG', label: 'Kyrgyzstan'},
    { value: 'LA', label: 'Laos'},
    { value: 'LV', label: 'Latvia'},
    { value: 'LB', label: 'Lebanon'},
    { value: 'LS', label: 'Lesotho'},
    { value: 'LR', label: 'Liberia'},
    { value: 'LY', label: 'Libya'},
    { value: 'LI', label: 'Liechtenstein'},
    { value: 'LT', label: 'Lithuania'},
    { value: 'LU', label: 'Luxembourg'},
    { value: 'MK', label: 'North Macedonia'},
    { value: 'MG', label: 'Madagascar'},
    { value: 'MW', label: 'Malawi'},
    { value: 'MY', label: 'Malaysia'},
    { value: 'MV', label: 'Maldives'},
    { value: 'ML', label: 'Mali'},
    { value: 'MT', label: 'Malta'},
    { value: 'MH', label: 'Marshall Islands'},
    { value: 'MR', label: 'Mauritania'},
    { value: 'MU', label: 'Mauritius'},
    { value: 'MX', label: 'Mexico'},
    { value: 'FM', label: 'Micronesia'},
    { value: 'MD', label: 'Moldova'},
    { value: 'MC', label: 'Monaco'},
    { value: 'MN', label: 'Mongolia'},
    { value: 'ME', label: 'Montenegro'},
    { value: 'MA', label: 'Morocco'},
    { value: 'MZ', label: 'Mozambique'},
    { value: 'MM', label: 'Myanmar'},
    { value: 'NA', label: 'Namibia'},
    { value: 'NR', label: 'Nauru'},
    { value: 'NP', label: 'Nepal'},
    { value: 'NL', label: 'Netherlands'},
    { value: 'NZ', label: 'New Zealand'},
    { value: 'NI', label: 'Nicaragua'},
    { value: 'NE', label: 'Niger'},
    { value: 'NG', label: 'Nigeria'},
    { value: 'NO', label: 'Norway'},
    { value: 'OM', label: 'Oman'},
    { value: 'PK', label: 'Pakistan'},
    { value: 'PW', label: 'Palau'},
    { value: 'PS', label: 'Palestine'},
    { value: 'PA', label: 'Panama'},
    { value: 'PG', label: 'Papua New Guinea'},
    { value: 'PY', label: 'Paraguay'},
    { value: 'PE', label: 'Peru'},
    { value: 'PH', label: 'Philippines'},
    { value: 'PL', label: 'Poland'},
    { value: 'PT', label: 'Portugal'},
    { value: 'QA', label: 'Qatar'},
    { value: 'RO', label: 'Romania'},
    { value: 'RU', label: 'Russia'},
    { value: 'RW', label: 'Rwanda'},
    { value: 'KN', label: 'Saint Kitts and Nevis'},
    { value: 'LC', label: 'Saint Lucia'},
    { value: 'VC', label: 'Saint Vincent and the Grenadines'},
    { value: 'WS', label: 'Samoa'},
    { value: 'SM', label: 'San Marino'},
    { value: 'ST', label: 'São Tomé and Príncipe'},
    { value: 'SA', label: 'Saudi Arabia'},
    { value: 'SN', label: 'Senegal'},
    { value: 'RS', label: 'Serbia'},
    { value: 'SC', label: 'Seychelles'},
    { value: 'SL', label: 'Sierra Leone'},
    { value: 'SG', label: 'Singapore'},
    { value: 'SK', label: 'Slovakia'},
    { value: 'SI', label: 'Slovenia'},
    { value: 'SB', label: 'Solomon Islands'},
    { value: 'SO', label: 'Somalia'},
    { value: 'ZA', label: 'South Africa'},
    { value: 'SS', label: 'South Sudan'},
    { value: 'ES', label: 'Spain'},
    { value: 'LK', label: 'Sri Lanka'},
    { value: 'SD', label: 'Sudan'},
    { value: 'SR', label: 'Suriname'},
    { value: 'SE', label: 'Sweden'},
    { value: 'CH', label: 'Switzerland'},
    { value: 'SY', label: 'Syria'},
    { value: 'TW', label: 'Taiwan'},
    { value: 'TJ', label: 'Tajikistan'},
    { value: 'TZ', label: 'Tanzania'},
    { value: 'TH', label: 'Thailand'},
    { value: 'TL', label: 'Timor-Leste'},
    { value: 'TG', label: 'Togo'},
    { value: 'TO', label: 'Tonga'},
    { value: 'TT', label: 'Trinidad and Tobago'},
    { value: 'TN', label: 'Tunisia'},
    { value: 'TR', label: 'Türkiye'},
    { value: 'TM', label: 'Turkmenistan'},
    { value: 'TV', label: 'Tuvalu'},
    { value: 'UG', label: 'Uganda'},
    { value: 'UA', label: 'Ukraine'},
    { value: 'AE', label: 'United Arab Emirates'},
    { value: 'GB', label: 'United Kingdom'},
    { value: 'US', label: 'United States'},
    { value: 'UY', label: 'Uruguay'},
    { value: 'UZ', label: 'Uzbekistan'},
    { value: 'VU', label: 'Vanuatu'},
    { value: 'VA', label: 'Vatican City'},
    { value: 'VE', label: 'Venezuela'},
    { value: 'VN', label: 'Vietnam'},
    { value: 'YE', label: 'Yemen'},
    { value: 'ZM', label: 'Zambia'},
    { value: 'ZW', label: 'Zimbabwe'}
  ];

  export const LOCATIONS = [
    { id: 1, name: 'Colombo' },
    { id: 2, name: 'Bentota' },
    { id: 3, name: 'Arugam Bay' },
    { id: 4, name: 'Anuradhapura' },
    { id: 5, name: 'Ella' },
    { id: 6, name: 'Little Adam\'s Peak' },
    { id: 7, name: 'Nine Arch Bridge' },
    { id: 8, name: 'Ravana Waterfalls' },
    { id: 9, name: 'Ravana Zipline' },
    { id: 10, name: 'Galle Fort' },
    { id: 11, name: 'Hikkaduwa' },
    { id: 12, name: 'Turtle Beach' },
    { id: 13, name: 'Horton Plains' },
    { id: 14, name: 'World\'s End (Sri Lanka)' },
    { id: 15, name: 'Kandy' },
    { id: 16, name: 'Ambuluwawa Tower' },
    { id: 17, name: 'Elephant Orphanage' },
    { id: 18, name: 'Temple of the Tooth Relic' },
    { id: 19, name: 'Royal Botanical Garden' },
    { id: 20, name: 'Kitulgala' },
    { id: 21, name: 'Mirissa' },
    { id: 22, name: 'Negombo' },
    { id: 23, name: 'Nuwara Eliya' },
    { id: 24, name: 'Damro Tea Factory' },
    { id: 25, name: 'Gregory Lake' },
    { id: 26, name: 'Ramboda Falls' },
    { id: 27, name: 'Tea Plantations' },
    { id: 28, name: 'Sigiriya' },
    { id: 29, name: 'Dambulla' },
    { id: 30, name: 'Habarana' },
    { id: 31, name: 'Kawudulla' },
    { id: 32, name: 'Pidurangala' },
    { id: 33, name: 'Minneriya' },
    { id: 34, name: 'Tangalle' },
    { id: 35, name: 'Hiriketiya' },
    { id: 36, name: 'Trincomalee' },
    { id: 37, name: 'Marble Bay' },
    { id: 38, name: 'Maritime & Naval History Museum' },
    { id: 39, name: 'Pasikuda' },
    { id: 40, name: 'ThiruKoneshwaram Kovil' },
    { id: 41, name: 'Udawalawa' },
    { id: 42, name: 'Weligama' },
    { id: 43, name: 'Yala' },
    { id: 44, name: 'Adam\'s Peak' }
  ];
  
  export const getFormattedCountryCodes = (countries, getCountryCallingCode) => {
    const formattedCountries = countries.map(country => {
      const code = `+${getCountryCallingCode(country)}`;
      return {
        value: code,
        label: `${code} (${country})`,
        country: country
      };
    });
    
    formattedCountries.sort((a, b) => {
      const codeA = parseInt(a.value.slice(1));
      const codeB = parseInt(b.value.slice(1));
      return codeA - codeB;
    });
    
    return formattedCountries;
  };