name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Setup Node.js (use version 18)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      # 3. Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm install
        working-directory: "Back End"

      # 4. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 5. Install Python dependencies (from itinerary/requirements.txt)
      - name: Install Python dependencies
        run: |
          cd "Back End/itinerary"
          pip install -r requirements.txt

      # 6. Run Node.js tests
      - name: Run Tests
        run: |
          cd "Back End"
          npm test

  deploy:
      7. Deploy using Railway or another service
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          npm install -g railway
          cd "Back End"
          railway up --token $RAILWAY_TOKEN --detach